<a href="https://colab.research.google.com/github/AnvarjonIbrohimov/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([1,3,5,2])
print("numpy_array:", arr)

numpy_array: [1 3 5 2]


In [5]:
arr2 = np.array([
    [1,3,5,2],
     [2,1,4,2]
    ])
print("numpy_array:", arr2)

numpy_array: [[1 3 5 2]
 [2 1 4 2]]


In [6]:
# dtype  qaysi type ekanni chiqarib beradi
a = np.array([1,2,3])
print(a.dtype)

int64


In [7]:
# reshape  2 row 3 columnga ozgartirib beradi
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
print("shaped_array:", b)

shaped_array: [[1 2 3]
 [4 5 6]]


In [10]:
# astype() typeni ozgartirib beradi
a = np.array([1,2,3])
b = a.astype(float)
print("float:", b)

float: [1. 2. 3.]


In [12]:
# np.zeros() typeni ozgartirib beradi
z = np.zeros((2,3))
o = np.ones((2,3))
print("zeros:", z)
print("ones:", o)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# ndin
a = np.array([[1,2], [3,4]])
print("ndin:", a.ndim)

ndin: 2


In [16]:
# arrange() => ketma ket array (1,6) 1 dan 6 gacha chiqarib ebradi 6 chiqmaydi
a = np.arange(1,6)
print("arange:", a)

arange: [1 2 3 4 5]


In [17]:
# sum() mean() max() min()
a = np.array([1,2,3,4,5,6])

print("sum:", a.sum())
print("mean:", a.mean())
print("max:", a.max())
print("min:", a.min())

sum: 21
mean: 3.5
max: 6
min: 1


In [19]:
# flatten( )
a = np.array([[1,2], [3,4]])
print('flatten:', a.flatten())

flatten: [1 2 3 4]


In [21]:
# T( )
a = np.array([[1,2], [3,4]])
print('transpose:', a.T)

transpose: [[1 3]
 [2 4]]


In [23]:
# dor() @
a = np.array([[1,2], [3,4]])
b = np.array([[2,4], [1,2]])
print("dot/multiplication:", a.dot(b))

dot/multiplication: [[ 4  8]
 [10 20]]


In [24]:
# random.rand()
a = np.random.rand(2,4) # => 0.0 / 1.0 included
print("random.rand(): ", a)

random.rand():  [[0.24936383 0.54133018 0.40031469 0.26736231]
 [0.05471437 0.37283573 0.04973041 0.68273723]]
